//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("libav/avcodec-52.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("libav/avdevice-52.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("libav/avfilter-1.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("libav/avformat-52.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("libav/avutil-50.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("libav/sdl.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("libav/stdole.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("libav/swscale-0.dll")]


