//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfVideoUploader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTxt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTxt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfVideoUploader.ResourceTxt", typeof(ResourceTxt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied to create log file. \nPlease try by running the Application as Administrator.
        /// </summary>
        internal static string AccessDeniedError {
            get {
                return ResourceManager.GetString("AccessDeniedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddVideoInformation.xml.
        /// </summary>
        internal static string AddVideoInfoXmlFile {
            get {
                return ResourceManager.GetString("AddVideoInfoXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7EAF06EA83DA2454528C747FC64128F9968296AC08E61FCCD052D464049EDDEFCE62B2ED069F1396AC27F7DA120E6A3FDE982ACA8B49A4E8735552303198E03250EFE9D36E9E5349D2E289FF18D6C919CAB81199B4B24B13ABDF70CBB53605C844B1ED2C4164D08B1B4392C526C3D49E4100C1399C052C986BA57392042AC468BF0DDFD7BA5B12AFC4F2FFC21F9DF83D75C054DC6DBC198B091AD0E8AFD49D7A8CBA1E6B1BEA6BE3E0A3B41DA51B79E0678A7B675D3183618229AF2D50650A8505E9EA106E8507156E53ECA07973D883152F3CF4A75EBA57576B50A56117E2B129C5734150D552B7519D28AA7368895C740444BFEC403C041F4BA207F1258786.
        /// </summary>
        internal static string ALiscenceKey {
            get {
                return ResourceManager.GetString("ALiscenceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoUploader.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost/VideoUploader.
        /// </summary>
        internal static string ApplicationUpdateURL {
            get {
                return ResourceManager.GetString("ApplicationUpdateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoUploader.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sudheer@concatsys.com.
        /// </summary>
        internal static string Aseed {
            get {
                return ResourceManager.GetString("Aseed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load settings.
        /// </summary>
        internal static string CannotLoadSettings {
            get {
                return ResourceManager.GetString("CannotLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock On.
        /// </summary>
        internal static string CapsLock {
            get {
                return ResourceManager.GetString("CapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will stop currently uploading file and clear all the items from all the queue. Are sure to continue?.
        /// </summary>
        internal static string ClearAllListsMessage {
            get {
                return ResourceManager.GetString("ClearAllListsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentExporting.xml.
        /// </summary>
        internal static string CurrentExporting {
            get {
                return ResourceManager.GetString("CurrentExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2.2.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Images.
        /// </summary>
        internal static string DestinationtoSave {
            get {
                return ResourceManager.GetString("DestinationtoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://admin.flickfusion.net/ava/php/appxml_dev.php.
        /// </summary>
        internal static string DevRequestUri {
            get {
                return ResourceManager.GetString("DevRequestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, downloading latest version..
        /// </summary>
        internal static string DownloadLatestMessage {
            get {
                return ResourceManager.GetString("DownloadLatestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string EnableSsl {
            get {
                return ResourceManager.GetString("EnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to encode the file.
        /// </summary>
        internal static string EncodingErrorMsg1 {
            get {
                return ResourceManager.GetString("EncodingErrorMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .File removed from the Que.
        /// </summary>
        internal static string EncodingErrorMsg2 {
            get {
                return ResourceManager.GetString("EncodingErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding task.
        /// </summary>
        internal static string ErrorAddingTask {
            get {
                return ResourceManager.GetString("ErrorAddingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumerics and underscore  allowed!.
        /// </summary>
        internal static string ErrorCustomPrefix {
            get {
                return ResourceManager.GetString("ErrorCustomPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file to converter is failed!.
        /// </summary>
        internal static string ErrorFileLoading {
            get {
                return ResourceManager.GetString("ErrorFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding failed, because of problem in opening converter.
        /// </summary>
        internal static string ErrorOpeningConverter {
            get {
                return ResourceManager.GetString("ErrorOpeningConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while populating Rooftop.
        /// </summary>
        internal static string ErrorPopulatingRoofTop {
            get {
                return ResourceManager.GetString("ErrorPopulatingRoofTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventLog.xml.
        /// </summary>
        internal static string EventFile {
            get {
                return ResourceManager.GetString("EventFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventLog.
        /// </summary>
        internal static string EventLog {
            get {
                return ResourceManager.GetString("EventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Exported !.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting...... Please wait!.
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Prefix to Export Images.
        /// </summary>
        internal static string ExportWarnig {
            get {
                return ResourceManager.GetString("ExportWarnig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExTractedVideosInfo.xml.
        /// </summary>
        internal static string ExTractedVideosInfo {
            get {
                return ResourceManager.GetString("ExTractedVideosInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file not exist, removing from the uploading list.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://ftp.flickfusion.net/.
        /// </summary>
        internal static string FTPPath {
            get {
                return ResourceManager.GetString("FTPPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP URI is wrong, please check the FTP details.
        /// </summary>
        internal static string FTPUriError {
            get {
                return ResourceManager.GetString("FTPUriError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the data, Please try again.
        /// </summary>
        internal static string GetServerData_Error {
            get {
                return ResourceManager.GetString("GetServerData_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection closed, please check your net connection.
        /// </summary>
        internal static string GetServerData_WebError {
            get {
                return ResourceManager.GetString("GetServerData_WebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageExtract.
        /// </summary>
        internal static string ImageExtract {
            get {
                return ResourceManager.GetString("ImageExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageInformation.xml.
        /// </summary>
        internal static string ImageInfoXmlFile {
            get {
                return ResourceManager.GetString("ImageInfoXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoUploaderInstaller.msi.
        /// </summary>
        internal static string InstallerName {
            get {
                return ResourceManager.GetString("InstallerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password. Please try again..
        /// </summary>
        internal static string InValidLogin {
            get {
                return ResourceManager.GetString("InValidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Extracted Images.
        /// </summary>
        internal static string keepExtracted {
            get {
                return ResourceManager.GetString("keepExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Saved Images.
        /// </summary>
        internal static string keepSaved {
            get {
                return ResourceManager.GetString("keepSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Uploaded Videos.
        /// </summary>
        internal static string KeepUploaded {
            get {
                return ResourceManager.GetString("KeepUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VedioUploaderLog.log.
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogFile.xlsx.
        /// </summary>
        internal static string LogFileXls {
            get {
                return ResourceManager.GetString("LogFileXls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invtest01@gmail.com.
        /// </summary>
        internal static string MailFrom {
            get {
                return ResourceManager.GetString("MailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        internal static string MailHost {
            get {
                return ResourceManager.GetString("MailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invtest12345.
        /// </summary>
        internal static string MailPassword {
            get {
                return ResourceManager.GetString("MailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        internal static string MailPort {
            get {
                return ResourceManager.GetString("MailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@@concatsys.com.
        /// </summary>
        internal static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops we encountered a problem, send log manually to support@concatsys.com.
        /// </summary>
        internal static string MsgMailFailed {
            get {
                return ResourceManager.GetString("MsgMailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail sent sucessfully.Our support team will fix soon!.
        /// </summary>
        internal static string MSgMailSentSucess {
            get {
                return ResourceManager.GetString("MSgMailSentSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of this app is available. Would you like to upgrade now?.
        /// </summary>
        internal static string MsgNewVersion {
            get {
                return ResourceManager.GetString("MsgNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to internet!.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Custom Prefix.
        /// </summary>
        internal static string noPrefix {
            get {
                return ResourceManager.GetString("noPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found!.
        /// </summary>
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock value not found.
        /// </summary>
        internal static string NoStock {
            get {
                return ResourceManager.GetString("NoStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaderPwd1!.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CFF59B52-8393-46AC-97C5-AD93C1449AB6}.
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://admin.flickfusion.net/ava/php/appxml.php.
        /// </summary>
        internal static string ProductionRequestURI {
            get {
                return ResourceManager.GetString("ProductionRequestURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordedVideos.
        /// </summary>
        internal static string RecordedVideos {
            get {
                return ResourceManager.GetString("RecordedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while removing the record from XML file: \n.
        /// </summary>
        internal static string RemovingXMLFile {
            get {
                return ResourceManager.GetString("RemovingXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Rooftop--.
        /// </summary>
        internal static string RoofTopSelect {
            get {
                return ResourceManager.GetString("RoofTopSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        internal static string SelectFileName {
            get {
                return ResourceManager.GetString("SelectFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Images are Selected!.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select video file.
        /// </summary>
        internal static string selectVideoFile {
            get {
                return ResourceManager.GetString("selectVideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.xml.
        /// </summary>
        internal static string SettingsFile {
            get {
                return ResourceManager.GetString("SettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoUploader.msi.
        /// </summary>
        internal static string SetupFile {
            get {
                return ResourceManager.GetString("SetupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to exit?.
        /// </summary>
        internal static string sure {
            get {
                return ResourceManager.GetString("sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to logout?.
        /// </summary>
        internal static string SureLogout {
            get {
                return ResourceManager.GetString("SureLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the remote server.
        /// </summary>
        internal static string UnableToConnect {
            get {
                return ResourceManager.GetString("UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Video feature is disabled. Please contact your Reseller to enable Live Video.
        /// </summary>
        internal static string UnAuthorizedInvetory {
            get {
                return ResourceManager.GetString("UnAuthorizedInvetory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Video feature is disabled. Please contact your Reseller to enable AD Video.
        /// </summary>
        internal static string UnAuthorizedNonInvetory {
            get {
                return ResourceManager.GetString("UnAuthorizedNonInvetory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string UnInstalCaption {
            get {
                return ResourceManager.GetString("UnInstalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Remove.
        /// </summary>
        internal static string UnInstalCaptionConfirm {
            get {
                return ResourceManager.GetString("UnInstalCaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to keep App data?.
        /// </summary>
        internal static string UninstalMessage {
            get {
                return ResourceManager.GetString("UninstalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you Remove Data no longer available... are you sure?.
        /// </summary>
        internal static string UninstalMessageConfirm {
            get {
                return ResourceManager.GetString("UninstalMessageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install latest version, Please contact application vendor.
        /// </summary>
        internal static string UpdateFailedMessage {
            get {
                return ResourceManager.GetString("UpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string UpdateLatestCaption {
            get {
                return ResourceManager.GetString("UpdateLatestCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated version is available. Do you want to install?.
        /// </summary>
        internal static string UpdateLatestMessage {
            get {
                return ResourceManager.GetString("UpdateLatestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while uploading.
        /// </summary>
        internal static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add files to upload queue.
        /// </summary>
        internal static string UploadError_AddQ {
            get {
                return ResourceManager.GetString("UploadError_AddQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the pending files to upload queue.
        /// </summary>
        internal static string UploadError_FileLoad {
            get {
                return ResourceManager.GetString("UploadError_FileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileUploadRecord.xml.
        /// </summary>
        internal static string UploadRecordFile {
            get {
                return ResourceManager.GetString("UploadRecordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaderAppUser.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --All Makes--.
        /// </summary>
        internal static string VehicleMakeAll {
            get {
                return ResourceManager.GetString("VehicleMakeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --All Models--.
        /// </summary>
        internal static string VehicleModelAll {
            get {
                return ResourceManager.GetString("VehicleModelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionFile.xml.
        /// </summary>
        internal static string VersionFile {
            get {
                return ResourceManager.GetString("VersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop App/VideoUploaderVersion/.
        /// </summary>
        internal static string VersionFTPFolderPath {
            get {
                return ResourceManager.GetString("VersionFTPFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://103.13.242.103/.
        /// </summary>
        internal static string VersionFTPHost {
            get {
                return ResourceManager.GetString("VersionFTPHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *HP2012*.
        /// </summary>
        internal static string VersionFTPPassword {
            get {
                return ResourceManager.GetString("VersionFTPPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://ftp.flickfusion.net/.
        /// </summary>
        internal static string VersionFTPProductionHost {
            get {
                return ResourceManager.GetString("VersionFTPProductionHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vidUpd!235.
        /// </summary>
        internal static string VersionFTPProductionPassword {
            get {
                return ResourceManager.GetString("VersionFTPProductionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videoappupdate.
        /// </summary>
        internal static string VersionFTPProductionUserName {
            get {
                return ResourceManager.GetString("VersionFTPProductionUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotpad.
        /// </summary>
        internal static string VersionFTPUserName {
            get {
                return ResourceManager.GetString("VersionFTPUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost/TestWebSite/Default.aspx.
        /// </summary>
        internal static string VersionInfoURL {
            get {
                return ResourceManager.GetString("VersionInfoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Click queue button to check the progress..
        /// </summary>
        internal static string VideoAddMessage {
            get {
                return ResourceManager.GetString("VideoAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VedioInformation.xml.
        /// </summary>
        internal static string VideoInfoXmlFile {
            get {
                return ResourceManager.GetString("VideoInfoXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to keep Extracted Images?.
        /// </summary>
        internal static string WarningkeepExtracted {
            get {
                return ResourceManager.GetString("WarningkeepExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to keep Saved Images?.
        /// </summary>
        internal static string WarningKeepSaved {
            get {
                return ResourceManager.GetString("WarningKeepSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to keep Uploaded Videos?.
        /// </summary>
        internal static string WarningKeepUploadedVideos {
            get {
                return ResourceManager.GetString("WarningKeepUploadedVideos", resourceCulture);
            }
        }
    }
}
